{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jpi.fullname" . }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          {{- if kindIs "string" . }}
          - path: {{ . | quote }}
            pathType: "Prefix"
            backend:
              service:
                name: {{ include "jpi.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- else }}
          - path: {{ .path | default "/" | quote }}
            pathType: {{ .pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ include "jpi.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
