replicaCount: 1

image:
  repository: ghcr.io/OWNER/jpi
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

# Application and secret defaults (non-sensitive defaults)
app:
  publicBaseUrl: "http://localhost:8080"

secrets:
  # These keys will be used to reference Kubernetes Secrets. Provide actual
  # secret values via a Kubernetes Secret in production. The values below are
  # safe non-sensitive defaults to use in development/test environments.
  jwtSecretKey: "mySecretKey1234567890123456789012345678901234567890"
  db:
    url: "jdbc:mariadb://localhost:3306/churchdb"
    username: "root"
    password: "root"
  rabbit:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
